# ss：基于TCP / UDP之上的一个安全加密与授权协议

# obfs插件：经典老插件，在ss协议基础之上多了一层长的像TLS协议的欺骗性的封装，所以不存在TLS4次握手问题，也无需TLS跳过TLS证书链校验问题。服务端收到该伪装后会直接解包拿到ss数据包处理

# v2ray-plugin：伪装了一层加了一层 WS / TLS / WSS 外观的插件 👍

# gost-plugin：类似v2ray-plugin

# shadow-tls：伪装成TLS握手，伪装更真实，ss中伪装最好的插件 👍

# restls：类似shadow-tls，更新更小众

# kcptun：解决的是高延迟、丢包、弱网下的传输体验，不是用于伪装的插件 👍