# 出站通用配置
# 是一条TCP连接走多条发起网络的线路，如：网线、WIFI、蜂窝网络，目标是容灾/聚合带宽
# 实现：将一个TCP请求的TCP数据子包，分发到不同的线路上，一部分走网线，一部分走WIFI...
# mptcp: true

# 开启TCP多路复用，最佳实践多长肥流的场景不要开启它，TCP多路复用存在TCP队头堵塞问题，会拖慢整体TCP数据包的传输效率
# ⚠️ smux是叠加在这些代理协议之上的额外层，需要伪装代理协议服务端也支持才能生效
# smux

# 如果内核TCP支持tfo（TCP Fast Open），可以在建立3次握手后保留一个tfo cookie，下次建立连接带上该cookie即可直接连接，省去了前2次握手的交互，直接根据tfo + tfo cookie发送数据
# ⚠️ 需要client、server两端都支持才可用，否则回退到tcp普通的握手连接方式
# tfo: true