payload:
  - DOMAIN-SUFFIX,xiaoqinvar.cn
  - DOMAIN-SUFFIX,jybill.top
  - DOMAIN-SUFFIX,icoa.cn
  - DOMAIN-SUFFIX,icoa.vip
  - DOMAIN-SUFFIX,colab.dev
  
  - DOMAIN-KEYWORD,devtunnels

  - DOMAIN-KEYWORD,prettier
  - DOMAIN-KEYWORD,eslint
  
  - PROCESS-NAME,Obsidian Helper
  - PROCESS-NAME,Notion Helper
  - PROCESS-NAME,verge-mihomo
  - PROCESS-NAME,Raycast
  - PROCESS-NAME,Discord Helper